#!/usr/bin/env python
from gym import envs
envids = [spec.id for spec in envs.registry.all()]
for envid in sorted(envids):
    if str(envid)=='BaxterReacher-v0':  #add by Hansry
       print('BaxterReacherEnv')
#    print(envid)
